Refactor your code
tomasesquivelgc/OOP-Library pull request #6
Opened 2023-10-09 22:45 UTC by tomasesquivelgc

# In this branch
 Together with my partners @Rebelzob and @ivangonzalez224 have refactored some major parts of the code I originally worked on to follow SOLID principles.
 - We have created separate classes responsible for the creation and listing of users and books.
 - Ensured the code follows KISS, YAGNI and DRY principles
 - Refactored main.rb to minimize it's functions.

2023-10-09 23:08 UTC, Efiamotu-1 requested changes
Hi @tomasesquivelgc & @ivangonzalez224 & @Rebelzob , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-09 23:08 UTC, Efiamotu-1 commented on Project/create_user.rb
> +    person_type = gets.chomp.to_i
- [ ] To follow the `Single Responsibility Rule` for best practices all requests for input and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input. see the example code snippet below
- code snippet
```ruby
    print "Do you want to create a student (1) or a teacher (2)? [Input the number]: "
    person_type = gets.chomp
```
- [ ] Please kindly update your code base to follow this rule by implementing the above requirement everywhere in your app where you are requesting for user inputs :+1: :sparkles:

2023-10-09 23:08 UTC, Efiamotu-1 commented on Project/main.rb
> +    when 7 then exit
- [ ] Following the [reference video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) your project isn't following the correct order as shown below please i kindly suggest you make this necessary correction :+1: :sparkles: 
- project requirement
![order](https://github.com/tomasesquivelgc/OOP-Library/assets/89055502/5b39481c-e035-421f-a140-6d03072e6dbf)
- your project
![or](https://github.com/tomasesquivelgc/OOP-Library/assets/89055502/5c63d80e-291b-439c-ac5a-f28625db5b2d)

- [ ] Please Kindly ensure that your app follows all of the steps as spresented in the [reference video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) before resubmitting :+1: :sparkles:

2023-10-10 15:17 UTC, ivangonzalez224 commented on Project/main.rb
> +    when 7 then exit
Hi @Efiamotu-1 thank you for the review.
Changes done: 
- Corrected the order of the menu options.
- Changed the input requests and inputs validation to the interface file.

2023-10-10 15:51 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Team
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- Good refactoring :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 17:49 UTC, merged